# Generated by Django 6.0.3 on 2026-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "resumen",
                    models.TextField(help_text="Un breve resumen de la noticia"),
                ),
                ("contenido", models.TextField()),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Noticias",
            },
        ),
    ]
